/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sogrey_android_jni_md5_JNIUtils */

#ifndef _Included_sogrey_android_jni_md5_JNIUtils
#define _Included_sogrey_android_jni_md5_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sogrey_android_jni_md5_JNIUtils
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sogrey_android_1jni_1md5_JNIUtils_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     sogrey_android_jni_md5_JNIUtils
 * Method:    getMd5
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sogrey_android_1jni_1md5_JNIUtils_getMd5
        (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
